### PR TITLE
fix Dockerfile

### PR DESCRIPTION
**Pull request by hokuda**

### CODE REVIEW

**Comment by shyam-habarakada** [comment]
Thanks for the PR @hokuda — I completely missed the JDK I guess :-)

should we install a newer JDK? Ideas on how to support versions?

**Comment by hokuda** [comment]
JDK8 and 11 seems not compatible. So we need 11 for analysis against 11 runtime. I have no idea of a neat way to switch them.

**Comment by shyam-habarakada** [comment]
One idea is to publish docker images for 8, vs 11. So whoever can pick the right one.

**Comment by hokuda** [comment]
Good idea. so we can run pjdb, like:
`docker run -it -e JDB_OPTONS=$JDB_OPTIONS pjdb8`

**Pull request merged**
